apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: human-python-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: human-python-go 
  name: human-python-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: human-python-go 
